version: "3"

services:
  reporter_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 11111:11111
      - 22222:22222
    environment:
      - BuiltInCollector:UseDummyClient=false
