export const ASK_FOR_CPU_DATA = "ASK_FOR_CPU_DATA";
export const CPU_DATA_ARRIVED = "CPU_DATA_ARRIVED";
export const PC_INFO_ARRIVED = "PC_INFO_ARRIVED";

export default {
  ASK_FOR_CPU_DATA,
  CPU_DATA_ARRIVED,
  PC_INFO_ARRIVED,
};
